## **Modelling Random Forest**

## Load Data Final Hasil EDA & Preprocess untuk Modelling

In [18]:
import pandas as pd

df_model = pd.read_csv('../data/final for modelling/dataset_final_model.csv')

print('Shape Dataset Final untuk Modelling:', df_model.shape)

print('\nKolom dataset setelah encoding:')
print(df_model.columns.tolist())

display(df_model.head())

Shape Dataset Final untuk Modelling: (7679, 18)

Kolom dataset setelah encoding:
['tanggal', 'ISPU PM2.5', 'kategori_pm25', 'bulan', 'hari_minggu', 'temp', 'humidity', 'visibility', 'windgust', 'solarenergy', 'precip', 'station_bundaran hi', 'station_jagakarsa', 'station_kebun jeruk', 'station_kelapa gading', 'station_lubang buaya', 'station_us embassy 1', 'station_us embassy 2']

,tanggal,ISPU PM2.5,kategori_pm25,bulan,hari_minggu,temp,humidity,visibility,windgust,solarenergy,precip,station_bundaran hi,station_jagakarsa,station_kebun jeruk,station_kelapa gading,station_lubang buaya,station_us embassy 1,station_us embassy 2
0,2022-01-01,74.000000,Sedang,1,5,28.6,77.2,6.7,37.1,20.6,0.496,1,0,0,0,0,0,0
1,2022-01-01,73.000000,Sedang,1,5,28.3,77.8,6.8,37.1,20.6,0.502,0,1,0,0,0,0,0
2,2022-01-01,71.000000,Sedang,1,5,28.3,79.3,7.5,37.1,20.6,0.645,0,0,1,0,0,0,0
3,2022-01-01,74.973893,Sedang,1,5,28.6,76.9,6.7,34.9,21.0,0.262,0,0,0,1,0,0,0
4,2022-01-01,80.000000,Sedang,1,5,28.5,76.8,6.2,34.9,21.0,0.451,0,0,0,0,1,0,0

## Split Train & Test

In [19]:
from sklearn.model_selection import train_test_split

# FITUR INPUT (X)
X = df_model.drop(columns=[
    'tanggal',
    'ISPU PM2.5',
    'kategori_pm25'
])

# TARGET OUTPUT (y)
y = df_model['ISPU PM2.5']

# TRAIN TEST SPLIT
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2, # 20% test, 80% train
    random_state=42
)

# CEK HASIL
print('Shape X_train :', X_train.shape)
print('Shape X_test  :', X_test.shape)
print('Shape y_train :', y_train.shape)
print('Shape y_test  :', y_test.shape)

Shape X_train : (6143, 15)
Shape X_test  : (1536, 15)
Shape y_train : (6143,)
Shape y_test  : (1536,)

In [20]:
# TAMPILKAN FITUR INPUT (X)
print('KOLOM FITUR INPUT (X)')
display(X.head())

# TAMPILKAN TARGET OUTPUT (y)
print('KOLOM TARGET OUTPUT (y)')
display(y.head())

KOLOM FITUR INPUT (X)

,bulan,hari_minggu,temp,humidity,visibility,windgust,solarenergy,precip,station_bundaran hi,station_jagakarsa,station_kebun jeruk,station_kelapa gading,station_lubang buaya,station_us embassy 1,station_us embassy 2
0,1,5,28.6,77.2,6.7,37.1,20.6,0.496,1,0,0,0,0,0,0
1,1,5,28.3,77.8,6.8,37.1,20.6,0.502,0,1,0,0,0,0,0
2,1,5,28.3,79.3,7.5,37.1,20.6,0.645,0,0,1,0,0,0,0
3,1,5,28.6,76.9,6.7,34.9,21.0,0.262,0,0,0,1,0,0,0
4,1,5,28.5,76.8,6.2,34.9,21.0,0.451,0,0,0,0,1,0,0

KOLOM TARGET OUTPUT (y)

0    74.000000
1    73.000000
2    71.000000
3    74.973893
4    80.000000
Name: ISPU PM2.5, dtype: float64

## Model Random Forest

In [15]:
## isi disini yah buat model dan training nya